spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO}

api:
  client:
    server:
      pedidoUri: ${URL_CLIENT_SERVER_PEDIDO}    
      pagamentoUri: ${URL_CLIENT_SERVER_PAGAMENTO}
      producaoUri: ${URL_CLIENT_SERVER_PRODUCAO}