spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO}

api:
  client:
    server:               
      pedidoUri: http://tech-challenge-microservico-pedido-service:8081/v1    
      pagamentoUri: http://tech-challenge-microservico-pagamento-service:8082/v1
      producaoUri: http://tech-challenge-microservico-producao-service:8083/v1