apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-gateway-service
  namespace: tech-challenge-pos-tech
  labels:
    app: tech-challenge-api-gateway
spec:
  selector:
    app: tech-challenge-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer